#Created by webjeda - http://webjeda.com

title: Never look back #Keep it short
email: screamingintothenight1@yahoo.com


#baseurl: /bheema

sass:
 style: compressed
 
 
# Tracker
analytics: UA-83979019-1
 
### exclude the instructions / write-up in the README.md
exclude:
- README.md
